### PR TITLE
maintain lastUsedTime so clients can use it as a factor in idle and …

### PR DESCRIPTION
**Pull request by ellulpatrick**
…health check logic

### CODE REVIEW

**Comment by jackc** [comment]
On my machine this change increases the time of an acquire and release by as much as 36% (371ns -> 505ns). This is almost entirely due to the `time.Now()` call. Now in absolute terms it is only an extra 134ns extra, but I'd still prefer to keep puddle as lean as possible.

Could you add this feature to a wrapper for puddle? That's the technique I am using in https://github.com/jackc/pgx/blob/master/pgxpool/pool.go to add health check functionality.

**Comment by ellulpatrick** [comment]
> Could you add this feature to a wrapper for puddle? That's the technique I am using in https://github.com/jackc/pgx/blob/master/pgxpool/pool.go to add health check functionality.

Hi @jackc . Thanks for getting back to me. That is the reason I needed to keep track of lastUsedTime.
Right now the backgroundHealthCheck  in pgxPool simply checks against maxConnLifetime. In production, we'd like to close connections that have not been used for duration x to avoid stale connections. Or perhaps we might also want to ping on such connections to keep them alive. This is why we need to keep track of when a connection was last used.  How would you recommend that we achieve this? Thanks in advance.

**Comment by jackc** [comment]
On further investigation, I found to my chagrin that in the existing implementation `time.Now()` calls were already consuming over 2/3s of the time in low contention benchmarks.

However, that lead me to finding a way to use `runtime.nanotime` directly which is significantly faster than `time.Now()`. By switching to that for duration measurements I was able merge in your changes without a slowdown. In fact, what was previously 371ns on master, and 505ns on the initial version of this is now only 244ns -- a full 1/3 faster.

I had to restructure your changes a bit to get this to work, but I think that the function `IdleDuration()` will now do exactly what you want.

**Comment by ellulpatrick** [comment]
@jackc, thank you. Glad that the investigation did not go to waste.
Looking forward to using this feature.

**Pull request merged**
