### PR TITLE
Create resources in the background in Acquire

### PR DESCRIPTION
**Pull request by jameshartig**
Modifies the behavior or creating resources in Acquire to do them asynchronously if the context is cancelled. For most constructors that handle context cancellation nothing changes but for constructors that ignore cancellation then new resources will continue to be created even if the Acquire is cancelled.

Fixes https://github.com/jackc/pgx/issues/1287

### CODE REVIEW

**Comment by jackc** [comment]
While testing this more locally I've run into a couple flickering test failures.

```
--- FAIL: TestPoolStatCanceledAcquireDuringCreate (0.05s)
    pool_test.go:653:
        	Error Trace:	/Users/jack/dev/puddle/pool_test.go:653
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestPoolStatCanceledAcquireDuringCreate
FAIL
FAIL	github.com/jackc/puddle/v2	3.129s
FAIL
```

This may just be due to the difficulty of testing concurrent code and not a real issue, but while I was looking into it further I found that `TestStress` will occasionally deadlock.

I'm looking into it now.

**Comment by jameshartig** [comment]
One issue is that I only did `p.canceledAcquireCount += 1` inside of the goroutine so it will only increment `canceledAcquireCount` when the actual constructor was cancelled. Maybe I should have incremented it outside of the goroutine instead?

**Comment by jameshartig** [comment]
I was able to reproduce a deadlock but I'm not sure how it happened yet:

```
=== RUN   TestStress
coverage: 59.1% of statements
panic: test timed out after 1m30s

goroutine 2478 [running]:
testing.(*M).startAlarm.func1()
	C:/Program Files/Go/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	C:/Program Files/Go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000047d40, {0x71897e, 0xa}, 0x7434e8)
	C:/Program Files/Go/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	C:/Program Files/Go/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc000047d40, 0xc000107b68)
	C:/Program Files/Go/src/testing/testing.go:1446 +0x217
testing.runTests(0xc000001360?, {0x8f49e0, 0x25, 0x25}, {0x40?, 0x1679b78?, 0x8fa2c0?})
	C:/Program Files/Go/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc000001360)
	C:/Program Files/Go/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:177 +0x3bd

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc000017de8?)
	C:/Program Files/Go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000017de0)
	C:/Program Files/Go/src/sync/waitgroup.go:139 +0xad
github.com/jackc/puddle/v2_test.TestStress(0xc000150000)
	c:/Users/james/Desktop/puddle/pool_test.go:917 +0x965
testing.tRunner(0xc000150000, 0x7434e8)
	C:/Program Files/Go/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1493 +0x75e

goroutine 10 [select]:
github.com/jackc/puddle/v2.(*Pool[...]).Acquire(0xc000152000, {0x795cf0, 0xc0000161a8})
	c:/Users/james/Desktop/puddle/pool.go:367 +0xdd9
github.com/jackc/puddle/v2_test.TestStress.func3()
	c:/Users/james/Desktop/puddle/pool_test.go:844 +0x79
github.com/jackc/puddle/v2_test.TestStress.func7()
	c:/Users/james/Desktop/puddle/pool_test.go:905 +0x74
created by github.com/jackc/puddle/v2_test.TestStress
	c:/Users/james/Desktop/puddle/pool_test.go:896 +0x6fb
FAIL	github.com/jackc/puddle/v2	90.144s
```

**Comment by jackc** [comment]
Seeing the same here. And I think I just found the issue. It is possible for the goroutine send:

```go
					select {
					case constructErrCh <- err:
					default:
					}
```

to be reached before the outer method gets to:

```go
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case err := <-constructErrCh:
				if err != nil {
					return nil, err
				}
				// we don't call signal here because we didn't change the resource pools
				// at all so waking anything else up won't help
				return res, nil
			}
```

**Comment by jackc** [comment]
You can reliably induce the deadlock with a `time.Sleep(time.Second)` before the outer method's select.

**Comment by jameshartig** [comment]
Yeah I just realized the same. Want to just move that above the goroutine and move the cancellation increment as well? Should fix the issue. Apologies I didn't realize that before.

**Comment by jackc** [comment]
> Yeah I just realized the same. Want to just move that above the goroutine and move the cancellation increment as well? 

Above? I thought it would have to go below? Maybe were not thinking of the same thing.

---

Thinking more about the original issue it makes me wonder if there is a more fundamental issue with puddle.

Right now, if creating a resource takes 2 seconds and every `Acquire()` call has a context with a 1 second timeout then no resources will ever be created. This patch allows the caller to work around that with a detached context. But this introduces another deadlock or long delay when the pool is closed. `Close()` is a blocking operation that waits until all resources are closed. There is no way to signal that we *really* do want to cancel the resource creation. So it would hang until those background constructor calls returned. (and maybe `Close()` shouldn't be blocking).

Also, the caller really shouldn't have deal with setting up a detached context.

I'm beginning to think that the fundamental issue is that all resource creations should be in the background. The context from Acquire should not be passed to the constructor at all. The context passed to the constructor should be a pool context that is closed when the pool is closed.

Not sure that's an acceptable change for a non-major release though. It's possible someone is relying on that the context passing from `Acquire()` into the constructor. Maybe we finish this fix for puddle v1 / pgx v4 and make the major change for puddle v2 / pgx v5.

**Comment by jameshartig** [comment]
> Above? I thought it would have to go below? Maybe were not thinking of the same thing.

Actually maybe just add ctx.Done to that select and remove the default. That should fix it without having to reorganize anything. 

I don't disagree with disconnecting it from the context but I'd have to think on it more. There might be another way to signal shutdown or maybe an option to set on puddle to do the detaching for you but still keep it attached to shutdown.

**Comment by jameshartig** [comment]
Created #22 to address the race and fix the cancellation increment.

**Pull request merged**
